from selenium.webdriver import Chrome
from time import sleep

driver = Chrome("../pytestTy/chromedriver.exe")
driver.get("http://demowebshop.tricentis.com/")
sleep(5)
ele = driver.find_element_by_class_name('ico-register')
ele.click()
sleep(2)
# ele_xpath = driver.find_element_by_xpath("//a[@href = '/register']")
ele_ge = driver.find_element_by_id("gender-male")
ele_ge.click()
sleep(2)
ele_fn = driver.find_element_by_id("FirstName")
ele_fn.send_keys("vishnu")
sleep(2)
ele_ln = driver.find_element_by_id("LastName")
ele_ln.send_keys("kulkarni")
sleep(2)
ele_mail = driver.find_element_by_id("Email")
ele_mail.send_keys("hello123@gmail.com")
sleep(2)
ele_pass = driver.find_element_by_id("Password")
ele_pass.send_keys("123456")
sleep(2)
ele_cnf_pass = driver.find_element_by_id("ConfirmPassword")
ele_cnf_pass.send_keys("123456")
sleep(2)
ele_buut = driver.find_element_by_id("register-button")
ele_buut.click()
sleep(5)
driver.close()